spring.application.name=Ecom-project-1

spring.jpa.show-sql= true

spring.jpa.defer-datasource-initialization=true

spring.datasource.url=jdbc:mysql://localhost:3306/ecom_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


cloudinary.cloud_name=diwvz2swm
cloudinary.api_key=981841473676725
cloudinary.api_secret=KZL1xqjn1_7NnamCjAW6NQvMIT8